# Generated by Django 4.2 on 2025-05-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CityCached",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название города", max_length=124
                    ),
                ),
                ("latitude", models.FloatField(help_text="Широта города")),
                ("longitude", models.FloatField(help_text="Долгота города")),
                (
                    "country",
                    models.CharField(
                        help_text="Страна города", max_length=124
                    ),
                ),
            ],
        ),
    ]
